version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: destinlmincy-postgres
    environment:
      POSTGRES_USER: dlm
      POSTGRES_PASSWORD: simplepass
      POSTGRES_DB: destinlmincy_com_db
    ports:
      - "5433:5432"
    volumes:
      - destinlmincy_postgres_data:/var/lib/postgresql/data

volumes:
  destinlmincy_postgres_data:
